export const archiveSeasons = [
  {
    season: "Spring 2026",
    slug: "spring-2026",
    talks: [
      {
        title: "How to Think Like a Space Billionaire",
        speaker: "Valerie A. Olson",
        affiliation: "University of California, Irvine",
        date: "Tuesday, 17 February 2026",
        time: "10-11:30 EST",
        location: "Location: Online",
      },
      {
        title: "Italy's Participation in Spacelab: A Case of Space Diplomacy?",
        speaker: "Piero Messina",
        affiliation: "Università degli Studi di Padova",
        date: "Tuesday, 10 March 2026",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Eyes in the Sky: Inversion and Imagination from Earth to Satellite and Back",
        speaker: "Lilian Kroth",
        affiliation: "Université de Fribourg",
        date: "Tuesday, 14 April 2026",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Prelude to the Space Age? Tracing the Cosmic in European Art around 1900",
        speaker: "Christina Ntanovasili",
        affiliation: "Aarhus Universitet",
        comment: "Comment by Joes Segal (The Wende Museum)",
        date: "Tuesday, 12 May 2026",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
    ],
  },
  {
    season: "Fall 2025",
    slug: "fall-2025",
    talks: [
      {
        title: "History, Communication and the Global Imagination: A Roundtable in Honor of Martin J. Collins",
        speaker:
          "John Krige, Teasel Muir-Harmony, James Schwoch, James Merle Thomas, Adelheid Voskuhl",
        affiliation:
          "Georgia Institute of Technology, Smithsonian National Air and Space Museum, Northwestern University, Helen Frankenthaler Foundation, University of Pennsylvania",
        comment: "Chair: Alexander C.T. Geppert (New York University/NYU Shanghai)",
        date: "Tuesday, 16 September 2025",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Territory beyond Earth: Expansionist Cosmic Imaginaries and the China Dream",
        speaker: "Paloma Puente Lozano",
        affiliation: "Universidad Carlos III de Madrid",
        date: "Tuesday, 21 October 2025",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "The Post-Soviet Space Deal: Survival, Adaptation, Commercialization",
        speaker: "Olga Dubrovina",
        affiliation: "Università degli Studi di Milano",
        date: "Tuesday, 18 November 2025",
        time: "10-11:30 EST",
        location: "Location: Online",
      },
      {
        title: "'New Planet, Dad. Please!' Multiplanetarity and Terralectics in Contemporary North American Astroculture",
        speaker: "Jens Temmen",
        affiliation: "Katholische Universität Eichstätt-Ingolstadt",
        date: "Tuesday, 2 December 2025",
        time: "10-11:30 EST",
        location: "Location: Online",
      },
    ],
  },
  {
    season: "Spring 2025",
    slug: "spring-2025",
    talks: [
      {
        title: "History and Narrative in China's Space Program",
        speaker: "Tonio Savina",
        affiliation: "Sapienza Università di Roma",
        date: "Tuesday, 18 February 2025",
        time: "10-11:30 EST",
        location: "Location: Online",
      },
      {
        title: "Where Were They? The Search for Extraterrestrial Intelligence in the First Space Age",
        speaker: "Robert Poole",
        affiliation: "University of Central Lancashire",
        date: "Tuesday, 18 March 2025",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "The Société Astronomique de France: A Global Popular Astronomy Network in the Belle Époque",
        speaker: "Laurence Guignard",
        affiliation: "Université Paris-Est Créteil",
        date: "Tuesday, 15 April 2025",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Space on Display: A Conversation among Curators",
        speaker:
          "Aron Schöpf, Doug Millard, Margaret Weitekamp",
        affiliation:
          "Deutsches Museum, Science Museum, Smithsonian National Air and Space Museum",
        comment: "Moderation: Alexander C.T. Geppert (NYU/NYU Shanghai)",
        date: "Tuesday, 20 May 2025",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
    ],
  },
  {
    season: "Fall 2024",
    slug: "fall-2024",
    talks: [
      {
        title: "Heralds of the Search for Extraterrestrial Intelligence: The C/SETI Novel",
        speaker: "De Witt Douglas Kilgore",
        affiliation: "Indiana University",
        date: "Wednesday, 11 September 2024",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Whither a Planetary Turn? A Roundtable",
        speaker:
          "Thore Bjørnvig, Alexander C.T. Geppert, Haitian Ma, Tilmann Siebeneichner, Brad Tabas",
        affiliation:
          "Copenhagen, NYU/NYU Shanghai, Universiteit van Amsterdam, ZZF Potsdam, ENSTA Bretagne",
        comment: "Moderation: Fabienne Will (Deutsches Museum)",
        date: "Wednesday, 9 October 2024",
        time: "12-13:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Computer World: Satellites, Planetization and Pixelation",
        speaker: "Mia Bennett",
        affiliation: "University of Washington",
        date: "Wednesday, 6 November 2024",
        time: "10-11:30 EST",
        location: "Location: Online",
      },
      {
        title: "New Directions in NASA History",
        speaker: "Brian Odom",
        affiliation: "NASA",
        date: "Wednesday, 4 December 2024",
        time: "10-11:30 EST",
        location: "Location: Online",
      },
    ],
  },
  {
    season: "Spring 2024",
    slug: "spring-2024",
    talks: [
      {
        title: "Interplanetary Contamination: Insights from Apollo for Asteroids, Artemis and Mars",
        speaker: "Jonathan B. Wiener",
        affiliation: "Duke University",
        date: "Wednesday, 21 February 2024",
        time: "10-11:30 EST",
        location: "Location: Online",
      },
      {
        title: "Words in Orbit: A Linguistic Inquiry into Outer Space",
        speaker: "Kajsa Törmä",
        affiliation: "Umeå universitet",
        date: "Wednesday, 13 March 2024",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "SETI during the Cold War: The Prague Spring and an International Symposium that Wasn't",
        speaker: "Gabriela Radulescu",
        affiliation: "Technische Universität Berlin",
        date: "Wednesday, 10 April 2024",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Cosmism: A Spiritual Reenchantment of Technological Modernity",
        speaker: "Juliette Faure",
        affiliation: "Sciences Po/Université Paris II Panthéon-Assas",
        comment: "Comment by Michael Hagemeister (Ruhr-Universität Bochum)",
        date: "Wednesday, 8 May 2024",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
    ],
  },
  {
    season: "Fall 2023",
    slug: "fall-2023",
    talks: [
      {
        title: "Mexico in Orbit: Modernity, Nationality and Satellite Fetishism",
        speaker: "Anne W. Johnson",
        affiliation: "Universidad Iberoamericana",
        date: "Wednesday, 13 September 2023",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Woman/Astronaut: Sally Ride, Work and Gender in Space",
        speaker: "Michèle Matetschk",
        affiliation: "Humboldt-Universität zu Berlin",
        date: "Thursday, 5 October 2023",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Politics, Personalities and Space Programs: The Case of Japan",
        speaker: "Brian Harvey",
        affiliation: "FBIS",
        date: "Wednesday, 8 November 2023",
        time: "10-11:30 EST",
        location: "Location: Online",
      },
      {
        title: "The LDEF: How a Returned Satellite Changed the Perception of Near-Earth Space",
        speaker: "Luca Thanei",
        affiliation: "ETH Zürich",
        date: "Wednesday, 29 November 2023",
        time: "10-11:30 EST",
        location: "Location: Online",
      },
    ],
  },
  {
    season: "Spring 2023",
    slug: "spring-2023",
    talks: [
      {
        title: "Historicizing the European Space Agency: An Archival Overview, 1987-2000",
        speaker: "Gherardo Bonini",
        affiliation: "Historical Archives of the European Union, Florence",
        date: "Wednesday, 22 February 2023",
        time: "10-11:30 EST",
        location: "Location: Online",
      },
      {
        title: "Rocket Boys: Space Enthusiasm in Early 1960s France",
        speaker: "Catherine Radtka",
        affiliation: "Conservatoire national des arts et métiers, Paris",
        date: "Wednesday, 22 March 2023",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Remaining in the Cradle: Amateurs and Children in Space",
        speaker: "Denis Sivkov",
        affiliation: "Russian Academy of National Economy and Public Administration, Moscow",
        date: "Wednesday, 19 April 2023",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Planetizing History",
        speaker: "Alexander C.T. Geppert and Brad Tabas",
        affiliation: "NYU/NYU Shanghai and ENSTA Bretagne",
        comment: "Moderation: Anne Johnson (Universidad Iberoamericana)",
        date: "Thursday, 11 May 2023",
        time: "10-11:30 EDT",
        location: "Location: Online",
      },
    ],
  },
  {
    season: "Fall 2022",
    slug: "fall-2022",
    talks: [
      {
        title: "'The Widest Practical and Appropriate Dissemination of Information:' Origins and Operations of NASA's History Program",
        speaker: "William P. Barry",
        affiliation: "former NASA Chief Historian",
        date: "Tuesday, 13 September 2022",
        time: "10:00-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "How (Not) to Become a Superpower in Space: Spacelab, Europe and the Politics of Post-Apollo, 1972-1987",
        speaker: "Tilmann Siebeneichner",
        affiliation: "Zentrum für Zeithistorische Forschung Potsdam",
        date: "Tuesday, 18 October 2022",
        time: "10:00-11:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Aliens in Mexico! Extraterrestrials, Astroculture and Space Imaginaries",
        speaker: "Gloria Maritza Gómez Revuelta",
        affiliation: "El Colegio de México",
        date: "Tuesday, 1 November 2022",
        time: "10:00-11:30 EDT",
        location: "Location: Online",
      },
    ],
  },
  {
    season: "Spring 2022",
    slug: "spring-2022",
    talks: [
      {
        title: "How to Paint What You Can't See: Astronomical Illustration in the Space Age",
        speaker: "Lois Rosson",
        affiliation: "University of California, Berkeley",
        date: "Thursday, 24 February 2022",
        time: "12:00-13:30 EST",
        location: "Location: Online",
      },
      {
        title: "The Cosmo-Political: Rethinking the Political in Outer Space",
        speaker: "Rory Rowan",
        affiliation: "Trinity College Dublin",
        date: "Friday, 8 April 2022",
        time: "12:00-13:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Demonstrating Friendship, Showcasing Parity: Decision-Making in the Apollo-Soyuz Test Project",
        speaker: "Darina Volf",
        affiliation: "Ludwig-Maximilians Universität München",
        date: "Thursday, 14 April 2022",
        time: "12:00-13:30 EDT",
        location: "Location: Online",
      },
      {
        title: "The Intellectual Roots of Space Law: Jurists, Astroculture and Internationalism in the 1950s and 1960s",
        speaker: "François Rulier",
        affiliation: "Université Jean Jaurès, Toulouse",
        date: "Thursday, 12 May 2022",
        time: "12:00-13:30 EDT",
        location: "Location: Online",
      },
    ],
  },
  {
    season: "Fall 2021",
    slug: "fall-2021",
    talks: [
      {
        title: "When Did Space Turn Dark?",
        speaker: "Vladimir Brljak",
        affiliation: "Durham University",
        date: "Thursday, 23 September 2021",
        time: "14:00-15:30 EDT",
        location: "Location: Online",
      },
      {
        title: "Playing Utopia, Performing Nostalgia? The Contemporary Appeal of Space Race Science Fiction Cinema",
        speaker: "Natalija Majsova",
        affiliation: "University of Ljubljana",
        date: "Thursday, 21 October 2021",
        time: "14:00-15:30 EDT",
        location: "Location: Online",
      },
      {
        title: "The Limits of Human Reality and the Senses of Outer Space: Philosophical Anthropology and the Study of Astroculture",
        speaker: "Brad Tabas",
        affiliation: "ENSTA Bretagne",
        date: "Thursday, 11 November 2021",
        time: "14:00-15:30 EST",
        location: "Location: Online",
      },
      {
        title: "Rocket Stars in the Global Space Age: Clarke, Qian, Sarabhai, Jähn, Merbold and Tamayo",
        speaker:
          "Alexander Geppert, Maritza Gómez, Lu Liu, Haitian Ma, Asif Siddiqi, Tilmann Siebeneichner and David Skogerboe",
        affiliation:
          "NYU/Caltech, Colegio de México, Georgia Institute of Technology, University of Amsterdam, Fordham University, Humboldt-Universität zu Berlin and Utrecht University",
        date: "Friday, 3 December 2021",
        time: "12:00-14:00 EST",
        location: "Location: Online",
      },
    ],
  },
  {
    season: "Summer 2021",
    slug: "summer-2021",
    talks: [],
  },
  {
    season: "Spring 2021",
    slug: "spring-2021",
    talks: [],
  },
];

export const talks = [
  {
    title:
      "A Mountain in Space: Taixu and the Buddhist Imagination of the Cosmos",
    speaker: "Ben Van Overmeire",
    affiliation: "Duke Kunshan University",
    date: "Tuesday, 15 September 2026",
    time: "10-11:30 EDT",
  },
  {
    title:
      "SETI@home 2.0: UFOs, Politics and the Science of Extraterrestrial Intelligence",
    speaker: "Christian Peters",
    affiliation: "Universität Bremen",
    comment: "Comment by Thore Bjørnvig (Copenhagen)",
    date: "Tuesday, 13 October 2026",
    time: "10-11:30 EDT",
  },
  {
    title:
      "The Kuafu Paradox: Why China's Flagship Solar Mission Failed to Launch",
    speaker: "Zhihui Zhang",
    affiliation: "Chinese Academy of Sciences",
    comment: "Comment by Zuoyue Wang (California State Polytechnic University)",
    date: "Tuesday, 3 November 2026",
    time: "10-11:30 EST",
  },
  {
    title:
      "When Is a Planet Just Right? Su-Shu Huang and the Concept of the Habitable Zone",
    speaker: "Michael Robinson",
    affiliation: "University of Hartford",
    date: "Tuesday, 1 December 2026",
    time: "10-11:30 EST",
  },
];
